pub use qiniu_http::{Error, ErrorKind, HeaderName, HeaderValue, Headers, Method};
mod client;
pub(crate) use client::Client;
pub mod domains_manager;
pub use domains_manager::{Choice, DomainsManager, DomainsManagerBuilder};
mod handler;
mod middleware;
pub(crate) mod request;
mod response;
pub(crate) use response::Response;
mod token;
pub use handler::{HTTPHandler, PanickedHTTPCaller};
pub use middleware::{HTTPAfterAction, HTTPAfterActionHandler, HTTPBeforeAction, HTTPBeforeActionHandler};
pub(crate) use token::Token;
