# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'fileutils'

task default: :spec

desc 'Generate Doc'
task :generate_doc do
  doc_dir = File.join('..', 'target', 'doc', 'qiniu_ng_ruby').freeze
  FileUtils.rm_r doc_dir, force: true, secure: true, verbose: true
  FileUtils.mkdir_p doc_dir, verbose: true
  sh 'bundle', 'exec', 'yard', 'doc', '--fail-on-warning', '--output-dir', File.expand_path(doc_dir, __dir__),
                                      '--exclude', "^#{Regexp.escape('lib/qiniu_ng/bindings.rb')}$"
end

desc 'Generate FFI Bindings'
task :generate_bindings do
  Dir.chdir File.expand_path(File.join('..', 'qiniu-c-translator'), __dir__) do
    sh 'cargo', 'run', '--',
       '--header-file', File.expand_path(File.join('..', 'qiniu-c', 'libqiniu_ng.h'), __dir__),
       'generate-ruby-bindings',
       '--output', File.expand_path(File.join('lib', 'qiniu_ng', 'bindings.rb'), __dir__)
  end
end
